Repository meta-pytorch/torchx, pull requests merged in 2023-07, with the labels that each got.

#742 Spellings
  torchx/schedulers/api.py
  torchx/schedulers/local_scheduler.py
  torchx/specs/api.py
Labels: CLA Signed, fb-exported

#745 ci: use larger instances to avoid docker disk space issues
  .github/workflows/aws-batch-integration-tests.yaml
  .github/workflows/components-integration-tests.yaml
  .github/workflows/python-unittests.yaml
Labels: docker

#739 make rdzv_backend configurable
  torchx/components/dist.py
Labels: CLA Signed

#746 docs: aws_batch/kfp fix dead links + change user agent to avoid 403
  docs/source/conf.py
  torchx/pipelines/kfp/adapter.py
  torchx/schedulers/aws_batch_scheduler.py
Labels: documentation, CLA Signed

#747 dev-requirements: bump kfp version to 1.8.22 to fix PyYaml issue
  dev-requirements.txt
Labels: CLA Signed, dependencies

#743 docker: Upgrade pytorch to 2.0
  torchx/runtime/container/Dockerfile
Labels: CLA Signed
